#######################################
#             Variable                #
#######################################
## Some variables for convenience:
variables:
# Used when the tests it runs depend only on mongod, mongos, the jstestshell and the tools.
# THIS HAS COPIES IN
# - etc/evergreen_yml_components/definitions.yml
# - etc/evergreen_yml_components/tasks/components/aggregation_framework/resmoke_tasks.yml
# - etc/evergreen_yml_components/tasks/components/change_streams/resmoke_tasks.yml
# - etc/evergreen_yml_components/tasks/components/field_level_encryption/resmoke_tasks.yml
# - etc/evergreen_yml_components/tasks/components/querying/resmoke_tasks.yml
# - etc/evergreen_yml_components/tasks/components/security/resmoke_tasks.yml
# ANY MODIFICATIONS HERE SHOULD ALSO BE MADE IN THOSE FILES
- &task_template
  name: template
  depends_on:
  - name: archive_dist_test_debug
  commands:
  - func: "do setup"
  - func: "run tests"
    vars:
      resmoke_args: --help
      resmoke_jobs_max: 0  # No cap on number of jobs.

# THIS HAS COPIES IN
# - etc/evergreen_yml_components/definitions.yml
# - etc/evergreen_yml_components/tasks/components/aggregation_framework/resmoke_tasks.yml
# - etc/evergreen_yml_components/tasks/components/change_streams/resmoke_tasks.yml
# - etc/evergreen_yml_components/tasks/components/querying/resmoke_tasks.yml
# - etc/evergreen_yml_components/tasks/components/replication/resmoke_tasks.yml
# ANY MODIFICATIONS HERE SHOULD ALSO BE MADE IN THOSE FILES
- &gen_task_template
  name: gen_task_template
  depends_on:
  - name: version_gen
    variant: generate-tasks-for-version
    # This is added because of EVG-18211.
    # Without this we are adding extra dependencies on evergreen and it is causing strain
    omit_generated_tasks: true
  - name: archive_dist_test_debug
  commands:
  - func: "generate resmoke tasks"
    vars:
      resmoke_args: --help

# THIS HAS COPIES IN
# - etc/evergreen_yml_components/definitions.yml
# - etc/evergreen_yml_components/tasks/components/aggregation_framework/resmoke_tasks.yml
# ANY MODIFICATIONS HERE SHOULD ALSO BE MADE IN THOSE FILES
- &jstestfuzz_config_vars
  is_jstestfuzz: true
  num_files: 15
  num_tasks: 5  # Upperbound by `max_sub_suites` specified through the variant with each task still running `num_files` files.
  # It is error prone to require each fuzzer-related Evergreen task to need to override the
  # resmoke_args variable. However, the resmoke_args variable must be defined as a string in the
  # task generation configuration to satisfy mongodb/mongo-task-generator. We therefore specify an
  # empty string for the variable to reflect there are no additional arguments provided to resmoke
  # by default for the fuzzer-related tasks.
  resmoke_args: ""
  resmoke_jobs_max: 1
  should_shuffle: false
  continue_on_failure: false
  # Terminate the function when there has been no output to stdout for 30 minutes. E.g. when something is stuck in an infinite loop.
  # resmoke.py writes the test output to logkeeper and only writes to stdout when starting the next test.
  # resmoke.py not producing output on stdout means that the test is still running and presumably not going to finish.
  # Note that timeout_secs is different from exec_timeout_secs, which applies to a task and times out regardless of whether output has been written to stdout.
  timeout_secs: 1800

# Used for tests that invoke 'resmoke.py --suites=jstestfuzz*'.
# THIS HAS COPIES IN
# - etc/evergreen_yml_components/definitions.yml
# - etc/evergreen_yml_components/tasks/components/aggregation_framework/resmoke_tasks.yml
# ANY MODIFICATIONS HERE SHOULD ALSO BE MADE IN THOSE FILES
- &jstestfuzz_template
  name: jstestfuzz_template
  exec_timeout_secs: 14400 # Time out the task if it runs for more than 4 hours.
  depends_on:
  - name: version_gen
    variant: generate-tasks-for-version
    # This is added because of EVG-18211.
    # Without this we are adding extra dependencies on evergreen and it is causing strain
    omit_generated_tasks: true
  - archive_dist_test_debug
  commands:
  - func: "generate resmoke tasks"


#######################################
#               Tasks                 #
#######################################
tasks:
- <<: *task_template
  name: aggregation
  tags: ["assigned_to_component_aggregation_framework", "aggregation", "common"]
  commands:
  - func: "do setup"
  - func: "run tests"

- <<: *task_template
  name: aggregation_repeat_queries
  tags: ["assigned_to_component_aggregation_framework"]
  depends_on:
  - name: aggregation
  commands:
  - func: "do setup"
  - func: "run tests"

- <<: *task_template
  name: aggregation_disabled_optimization
  tags: ["assigned_to_component_aggregation_framework", "aggregation", "common"]
  depends_on:
  - name: aggregation
  commands:
  - func: "do setup"
  - func: "run tests"

- <<: *task_template
  name: aggregation_ese
  tags: ["assigned_to_component_aggregation_framework", "aggregation", "encrypt"]
  depends_on:
  - name: aggregation
  commands:
  - func: "do setup"
  - func: "run tests"

- <<: *task_template
  name: aggregation_ese_gcm
  tags: ["assigned_to_component_aggregation_framework", "aggregation", "encrypt", "gcm"]
  depends_on:
  - name: aggregation
  commands:
  - func: "do setup"
  - func: "run tests"

- <<: *task_template
  name: aggregation_auth
  tags: ["assigned_to_component_aggregation_framework", "aggregation", "auth", "common"]
  depends_on:
  - name: aggregation
  commands:
  - func: "do setup"
  - func: "run tests"

- <<: *task_template
  name: aggregation_facet_unwind_passthrough
  tags: ["assigned_to_component_aggregation_framework", "aggregation", "unwind"]
  depends_on:
  - name: aggregation
  commands:
  - func: "do setup"
  - func: "run tests"

- <<: *task_template
  name: aggregation_mongos_passthrough
  tags: ["assigned_to_component_aggregation_framework", "aggregation", "no_async"]
  depends_on:
  - name: aggregation
  commands:
  - func: "do setup"
  - func: "run tests"

- <<: *task_template
  name: aggregation_one_shard_sharded_collections
  tags: ["assigned_to_component_aggregation_framework", "aggregation", "no_async", "sharded"]
  depends_on:
  - name: aggregation
  commands:
  - func: "do setup"
  - func: "run tests"

- <<: *task_template
  name: aggregation_read_concern_majority_passthrough
  tags: ["assigned_to_component_aggregation_framework", "aggregation", "read_write_concern", "no_debug_mode"]
  depends_on:
  - name: aggregation
  commands:
  - func: "do setup"
  - func: "run tests"
    vars:
      resmoke_jobs_factor: 0.5

- <<: *gen_task_template
  name: aggregation_secondary_reads_gen
  tags: ["assigned_to_component_aggregation_framework", "aggregation", "secondary_reads"]
  commands:
  - func: "generate resmoke tasks"
    vars:
      use_large_distro: "true"
      resmoke_jobs_max: 1

- <<: *task_template
  name: aggregation_sharded_collections_passthrough
  tags: ["assigned_to_component_aggregation_framework", "aggregation", "common", "sharded"]
  depends_on:
  - name: aggregation
  commands:
  - func: "do setup"
  - func: "run tests"

- <<: *task_template
  name: aggregation_sharded_collections_causally_consistent_passthrough
  tags: ["assigned_to_component_aggregation_framework", "aggregation", "secondary_reads", "sharded"]
  depends_on:
  - name: aggregation
  commands:
  - func: "do setup"
  - func: "run tests"

- <<: *gen_task_template
  name: aggregation_unsplittable_collections_on_random_shard_passthrough
  # TODO SERVER-83445 Enable on non-all-feature-flag variants.
  tags: ["assigned_to_component_aggregation_framework", "unsplittable_collections"]
  depends_on:
  - name: aggregation
  commands:
  - func: "do setup"
  - func: "run tests"

- <<: *task_template
  name: aggregation_column_store_index_passthrough
  # TODO SERVER-75026 Remove the 'feature_flag_guarded' tag and ensure this suite is run on all
  # variants.
  tags: ["assigned_to_component_aggregation_framework", "aggregation", "sbe_only", "feature_flag_guarded"]
  depends_on:
  - name: aggregation
  commands:
  - func: "do setup"
  - func: "run tests"

## Standalone generational fuzzer for multiversion aggregation pipelines ##
- <<: *jstestfuzz_template
  name: aggregation_multiversion_fuzzer_gen
  tags: ["assigned_to_component_aggregation_framework", "aggfuzzer", "common", "multiversion", "require_npm", "random_name", "future_git_tag_incompatible"]
  commands:
  - func: "initialize multiversion tasks"
    vars:
      aggregation_multiversion_fuzzer_last_lts: last_lts
      aggregation_multiversion_fuzzer_last_continuous: last_continuous
  - func: "generate resmoke tasks"
    vars:
      <<: *jstestfuzz_config_vars
      num_files: 20
      num_tasks: 20
      resmoke_args: "--mongodSetParameters='{logComponentVerbosity: {command: 2}}'"
      npm_command: agg-fuzzer
      run_no_feature_flag_tests: "true"

## Standalone generational fuzzer for multiversion aggregation expressions ##
- <<: *jstestfuzz_template
  name: aggregation_expression_multiversion_fuzzer_gen
  tags: ["assigned_to_component_aggregation_framework", "aggfuzzer", "multiversion", "require_npm", "random_name"]
  commands:
  - func: "initialize multiversion tasks"
    vars:
      aggregation_expression_multiversion_fuzzer_last_lts: last_lts
      aggregation_expression_multiversion_fuzzer_last_continuous: last_continuous
  - func: "generate resmoke tasks"
    vars:
      <<: *jstestfuzz_config_vars
      num_files: 20
      num_tasks: 20
      resmoke_args: "--mongodSetParameters='{logComponentVerbosity: {command: 2}}'"
      npm_command: agg-expr-fuzzer
      run_no_feature_flag_tests: "true"

## Standalone generational fuzzer for checking optimized and unoptimized expression equivalence
- <<: *jstestfuzz_template
  name: aggregation_expression_optimization_fuzzer_gen
  tags: ["assigned_to_component_aggregation_framework", "aggfuzzer", "require_npm", "random_name"]
  commands:
  - func: "generate resmoke tasks"
    vars:
      <<: *jstestfuzz_config_vars
      num_files: 20
      num_tasks: 20
      jstestfuzz_vars: --diffTestingMode optimization
      suite: generational_fuzzer
      resmoke_args: "--mongodSetParameters='{logComponentVerbosity: {command: 2}}'"
      npm_command: agg-expr-fuzzer

## Standalone generational fuzzer for checking optimized and unoptimized aggregation pipelines
- <<: *jstestfuzz_template
  name: aggregation_optimization_fuzzer_gen
  tags: ["assigned_to_component_aggregation_framework", "aggfuzzer", "require_npm", "random_name"]
  commands:
  - func: "generate resmoke tasks"
    vars:
      <<: *jstestfuzz_config_vars
      num_files: 20
      num_tasks: 20
      jstestfuzz_vars: --diffTestingMode optimization
      suite: generational_fuzzer
      resmoke_args: "--mongodSetParameters='{logComponentVerbosity: {command: 2}}'"
      npm_command: agg-fuzzer

## Standalone fuzzer for checking wildcard index correctness ##
- <<: *jstestfuzz_template
  name: aggregation_wildcard_fuzzer_gen
  tags: ["assigned_to_component_aggregation_framework", "aggfuzzer", "common", "wildcard", "require_npm", "random_name"]
  commands:
  - func: "generate resmoke tasks"
    vars:
      <<: *jstestfuzz_config_vars
      num_files: 20
      num_tasks: 20
      jstestfuzz_vars: --diffTestingMode wildcard
      npm_command: agg-fuzzer
      suite: generational_fuzzer
      resmoke_args: "--mongodSetParameters='{logComponentVerbosity: {command: 2}}'"

# Disabled under SERVER-81088
# ## Standalone fuzzer for checking columnstore index correctness ##
# - <<: *jstestfuzz_template
#   name: aggregation_columnstore_fuzzer_gen
#   tags: ["assigned_to_component_aggregation_framework", "aggfuzzer", "common", "columnstore", "require_npm", "random_name", "sbe_only", "feature_flag_guarded"]
#   commands:
#   - func: "generate resmoke tasks"
#     vars:
#       <<: *jstestfuzz_config_vars
#       num_files: 20
#       num_tasks: 20
#       jstestfuzz_vars: --diffTestingMode columnstore
#       npm_command: agg-fuzzer
#       suite: generational_fuzzer
#       resmoke_args: "--mongodSetParameters='{logComponentVerbosity: {command: 2}}'"

## Standalone fuzzer for checking timeseries optimizations correctness ##
- <<: *jstestfuzz_template
  name: aggregation_timeseries_fuzzer_gen
  tags: ["assigned_to_component_aggregation_framework", "aggfuzzer", "common", "timeseries", "require_npm", "random_name", "no_debug_mode"]
  commands:
  - func: "generate resmoke tasks"
    vars:
      <<: *jstestfuzz_config_vars
      # We have seen some common scenarios where the generated pipelines take a while to run and can
      # hit some timeouts. We'll split 80000 pipelines across 80 files, compared to 80000 pipelines
      # across 20 files in the other generational agg fuzzers. This approach can be considered if we
      # see similar timeouts elsewhere. It is not well understood whether/how we could pass
      # 'numPipelines' as an argument in the yaml here, but it works as part of the
      # 'jstestfuzz_vars' argument string. If a future reader better understands this evergreen
      # integration, please update this comment and/or move numPipelines to a yaml arg here.
      num_files: 80
      num_tasks: 20
      jstestfuzz_vars: --diffTestingMode timeseries --numPipelines=1000
      npm_command: agg-fuzzer
      suite: generational_fuzzer
      resmoke_args: "--mongodSetParameters='{logComponentVerbosity: {command: 2}}'"

## Standalone fuzzer for checking Bonsai optimizations correctness vs SBE stage-builders ##
- <<: *jstestfuzz_template
  name: aggregation_bonsai_m2_vs_sbe_stagebuilders_fuzzer_gen
  tags: ["assigned_to_component_aggregation_framework", "aggfuzzer", "common", "bonsai", "require_npm", "random_name", "no_debug_mode", "feature_flag_guarded", "cqf_only"]
  commands:
  - func: "generate resmoke tasks"
    vars:
      <<: *jstestfuzz_config_vars
      num_files: 20
      num_tasks: 20
      jstestfuzz_vars: --diffTestingMode bonsai_m2_vs_sbe_stagebuilders
      npm_command: agg-fuzzer
      suite: generational_fuzzer
      resmoke_args: "--mongodSetParameters='{logComponentVerbosity: {command: 2}}'"

## Standalone fuzzer for checking Bonsai optimizations correctness vs Classic ##
- <<: *jstestfuzz_template
  name: aggregation_bonsai_m2_vs_classic_fuzzer_gen
  tags: ["assigned_to_component_aggregation_framework", "aggfuzzer", "common", "bonsai", "require_npm", "random_name", "no_debug_mode", "feature_flag_guarded", "cqf_only"]
  commands:
  - func: "generate resmoke tasks"
    vars:
      <<: *jstestfuzz_config_vars
      num_files: 20
      num_tasks: 20
      jstestfuzz_vars: --diffTestingMode bonsai_m2_vs_classic
      npm_command: agg-fuzzer
      suite: generational_fuzzer
      resmoke_args: "--mongodSetParameters='{logComponentVerbosity: {command: 2}}'"
