version: '3.0'

services:
        configsvr1:
                container_name: configsvr1
                hostname: configsvr1
                image: mongo-binaries:evergreen-latest-master
                volumes:
                  - ./logs/configsvr1:/var/log/mongodb/
                  - ./scripts:/scripts/
                  - ./data/configsvr1:/data/configdb/
                command: /bin/bash /scripts/configsvr_init.sh
                networks:
                        antithesis-net:
                                ipv4_address: 10.20.20.6
                                # Set the an IPv4 with an address of 10.20.20.130 or higher
                                # to be ignored by the fault injector
                                #

        configsvr2:
                container_name: configsvr2
                hostname: configsvr2
                image: mongo-binaries:evergreen-latest-master
                volumes:
                        - ./logs/configsvr2:/var/log/mongodb/
                        - ./scripts:/scripts/
                        - ./data/configsvr2:/data/configdb/
                command: /bin/bash /scripts/configsvr_init.sh
                networks:
                        antithesis-net:
                                ipv4_address: 10.20.20.7
                                # Set the an IPv4 with an address of 10.20.20.130 or higher
                                # to be ignored by the fault injector
                                #

        configsvr3:
                container_name: configsvr3
                hostname: configsvr3
                image: mongo-binaries:evergreen-latest-master
                volumes:
                        - ./logs/configsvr3:/var/log/mongodb/
                        - ./scripts:/scripts/
                        - ./data/configsvr3:/data/configdb/
                command: /bin/bash /scripts/configsvr_init.sh
                networks:
                        antithesis-net:
                                ipv4_address: 10.20.20.8
                                # Set the an IPv4 with an address of 10.20.20.130 or higher
                                # to be ignored by the fault injector
                                #

        database1:
                container_name: database1
                hostname: database1
                image: mongo-binaries:evergreen-latest-master
                volumes:
                  - ./logs/database1:/var/log/mongodb/
                  - ./scripts:/scripts/
                  - ./data/database1:/data/db/
                command: /bin/bash /scripts/database_init.sh Shard1
                networks:
                        antithesis-net:
                                ipv4_address: 10.20.20.3
                                # Set the an IPv4 with an address of 10.20.20.130 or higher
                                # to be ignored by the fault injector
                                #
        database2:
                container_name: database2
                hostname: database2
                image: mongo-binaries:evergreen-latest-master
                volumes:
                  - ./logs/database2:/var/log/mongodb/
                  - ./scripts:/scripts/
                  - ./data/database2:/data/db/
                command: /bin/bash /scripts/database_init.sh Shard1
                networks:
                        antithesis-net:
                                ipv4_address: 10.20.20.4
                                # Set the an IPv4 with an address of 10.20.20.130 or higher
                                # to be ignored by the fault injector
                                #
        database3:
                container_name: database3
                hostname: database3
                image: mongo-binaries:evergreen-latest-master
                volumes:
                  - ./logs/database3:/var/log/mongodb/
                  - ./scripts:/scripts/
                  - ./data/database3:/data/db/
                command: /bin/bash /scripts/database_init.sh Shard1
                networks:
                        antithesis-net:
                                ipv4_address: 10.20.20.5
                                # Set the an IPv4 with an address of 10.20.20.130 or higher
                                # to be ignored by the fault injector

        database4:
                container_name: database4
                hostname: database4
                image: mongo-binaries:evergreen-latest-master
                volumes:
                        - ./logs/database4:/var/log/mongodb/
                        - ./scripts:/scripts/
                        - ./data/database4:/data/db/
                command: /bin/bash /scripts/database_init.sh Shard2
                networks:
                        antithesis-net:
                                ipv4_address: 10.20.20.10
                                # Set the an IPv4 with an address of 10.20.20.130 or higher
                                # to be ignored by the fault injector
                                #
        database5:
                container_name: database5
                hostname: database5
                image: mongo-binaries:evergreen-latest-master
                volumes:
                        - ./logs/database5:/var/log/mongodb/
                        - ./scripts:/scripts/
                        - ./data/database5:/data/db/
                command: /bin/bash /scripts/database_init.sh Shard2
                networks:
                        antithesis-net:
                                ipv4_address: 10.20.20.11
                                # Set the an IPv4 with an address of 10.20.20.130 or higher
                                # to be ignored by the fault injector
                                #
        database6:
                container_name: database6
                hostname: database6
                image: mongo-binaries:evergreen-latest-master
                volumes:
                        - ./logs/database6:/var/log/mongodb/
                        - ./scripts:/scripts/
                        - ./data/database6:/data/db/
                command: /bin/bash /scripts/database_init.sh Shard2
                networks:
                        antithesis-net:
                                ipv4_address: 10.20.20.12
                                # Set the an IPv4 with an address of 10.20.20.130 or higher
                                # to be ignored by the fault injector

        mongos:
                container_name: mongos
                hostname: mongos
                image: mongo-binaries:evergreen-latest-master
                volumes:
                  - ./logs/mongos:/var/log/mongodb/
                  - ./scripts:/scripts/
                command: python3 /scripts/mongos_init.py
                depends_on:
                        - "database1"
                        - "database2"
                        - "database3"
                        - "database4"
                        - "database5"
                        - "database6"
                        - "configsvr1"
                        - "configsvr2"
                        - "configsvr3"
                networks:
                        antithesis-net:
                                ipv4_address: 10.20.20.9
                                # The subnet provided here is an example
                                # An alternative subnet can be used
        workload:
                container_name: workload
                hostname: workload
                image: workload:evergreen-latest-master
                volumes:
                  - ./logs/workload:/var/log/resmoke/
                  - ./scripts:/scripts/
                command: python3 /scripts/workload_init.py
                depends_on:
                        - "mongos"
                networks:
                        antithesis-net:
                                ipv4_address: 10.20.20.130
                                # The subnet provided here is an example
                                # An alternative subnet can be used
networks:
        antithesis-net:
                driver: bridge
                ipam:
                        config:
                        - subnet: 10.20.20.0/24
