version: '3.0'

services:
        database1:
                container_name: database1
                hostname: database1
                build: ./database
                image: database:evergreen-latest-master
                volumes:
                  - ./logs/database1:/var/log/mongodb/
                networks:
                        antithesis-net:
                                ipv4_address: 10.20.20.3
                                # Set the an IPv4 with an address of 10.20.20.130 or higher
                                # to be ignored by the fault injector
                                #
        database2:
                container_name: database2
                hostname: database2
                build: ./database
                image: database:evergreen-latest-master
                volumes:
                  - ./logs/database2:/var/log/mongodb/
                networks:
                        antithesis-net:
                                ipv4_address: 10.20.20.4
                                # Set the an IPv4 with an address of 10.20.20.130 or higher
                                # to be ignored by the fault injector
                                #
        database3:
                container_name: database3
                hostname: database3
                build: ./database
                image: database:evergreen-latest-master
                volumes:
                  - ./logs/database3:/var/log/mongodb/
                networks:
                        antithesis-net:
                                ipv4_address: 10.20.20.5
                                # Set the an IPv4 with an address of 10.20.20.130 or higher
                                # to be ignored by the fault injector

        workload:
                container_name: workload
                hostname: workload
                build: ./workload
                image: workload:evergreen-latest-master
                depends_on:
                        - "database1"
                        - "database2"
                        - "database3"
                networks:
                        antithesis-net:
                                ipv4_address: 10.20.20.130
                                # The subnet provided here is an example
                                # An alternative subnet can be used

networks:
        antithesis-net:
                driver: bridge
                ipam:
                        config:
                        - subnet: 10.20.20.0/24
