test_kind: js_test

selector:
  roots:
    - jstestfuzz/out/*.js

executor:
  archive:
    hooks:
      - CheckReplDBHash
      - CheckMetadataConsistencyInBackground
      - ValidateCollections
  config:
    shell_options:
      global_vars:
        TestData:
          # Other fuzzers test commands against sharded clusters with logical session ids.
          disableImplicitSessions: true
          transitioningConfigShard: true
      crashOnInvalidBSONError: ""
      objcheck: ""
  hooks:
    - class: ContinuousConfigShardTransition
    - class: RunQueryStats
      allow_feature_not_supported: true
    - class: FuzzerRestoreSettings
    - class: CheckReplDBHash
      shell_options:
        global_vars:
          TestData:
            skipValidationOnInvalidViewDefinitions: true
    - class: CheckMetadataConsistencyInBackground
    - class: ValidateCollections
      shell_options:
        global_vars:
          TestData:
            skipValidationOnInvalidViewDefinitions: true
            transitioningConfigShard: true
    - class: CheckRoutingTableConsistency
      shell_options:
        global_vars:
          TestData:
            mayForgeReshardingTempCollections: true
  fixture:
    class: ShardedClusterFixture
    mongos_options:
      set_parameters:
        enableTestCommands: 1
        internalQueryStatsRateLimit: -1
        internalQueryStatsErrorsAreCommandFatal: true
      verbose: ""
    mongod_options:
      set_parameters:
        disableLogicalSessionCacheRefresh: false
        enableTestCommands: 1
        transactionLifetimeLimitSeconds: 1
        writePeriodicNoops: 1
        internalQueryStatsRateLimit: -1
        internalQueryStatsErrorsAreCommandFatal: true
        # Manually set the random migration fail point so we can set a threshold for skipping
        # moveCollection to prevent "starving" random chunk migrations.
        failpoint.balancerShouldReturnRandomMigrations:
          data:
            skipMoveCollectionThreshold: 0.5
          mode: alwaysOn
        balancerMigrationsThrottlingMs: 100
      verbose: ""
    num_rs_nodes_per_shard: 1
    num_shards: 2
    config_shard: "any"
