test_kind: js_test

selector:
  roots:
  - jstests/serverless/*.js
  - jstests/serverless/change_streams/**/*.js
  - src/mongo/db/modules/*/jstests/serverless/**/*.js

executor:
  config:
    shell_options:
      nodb: ''
