base_suite: replica_sets_reconfig_jscore_passthrough
overrides:
  - "maintenance_ports.replica_sets_reconfig_maintenance_port_hooks"
  - "maintenance_ports.replica_sets_reconfig_fixture_maintenance_ports"
