base_suite: replica_sets_reconfig_kill_stepdown_terminate_jscore_passthrough
overrides:
  - "maintenance_ports.replica_sets_reconfig_kill_terminate_stepdown_maintenance_port_hooks"
  - "maintenance_ports.replica_sets_reconfig_fixture_maintenance_ports"
