base_suite: replica_sets_reconfig_jscore_stepdown_passthrough
overrides:
  - "maintenance_ports.replica_sets_reconfig_stepdown_maintenance_port_hooks"
  - "maintenance_ports.replica_sets_reconfig_fixture_maintenance_ports"
