base_suite: replica_sets_reconfig_kill_stepdown_terminate_jscore_passthrough
overrides:
  - "priority_ports.replica_sets_reconfig_terminate_priority_port_hooks"
  - "priority_ports.replica_sets_reconfig_fixture_priority_ports"
