build_variant_large_distro_exceptions:
  - amazon
  - amazon-linux2-arm64-static-compile
  - amazon2023
  - amazon2023-arm64
  - debian12
  - enterprise-amazon2023
  # TODO(SERVER-85904) - enterprise-amazon2023-lto
  - enterprise-amazon2023-arm64
  # TODO(SERVER-85904) - enterprise-amazon2023-arm64-lto
  - enterprise-debian12-64
  - enterprise-linux-64-amazon-ami
  - enterprise-macos
  - enterprise-macos-arm64
  - enterprise-rhel-8-64-bit
  - enterprise-rhel-8-64-bit-coverage
  - enterprise-rhel-81-ppc64le
  - enterprise-rhel-8-arm64
  - enterprise-rhel-83-s390x
  - enterprise-rhel-90-64-bit
  - enterprise-rhel-90-arm64
  - enterprise-suse15-64
  - enterprise-ubuntu1804-arm64
  - enterprise-ubuntu1804-ppc64le
  - enterprise-ubuntu1804-s390x
  - enterprise-ubuntu2004-arm64
  - enterprise-ubuntu2204-arm64
  - hot_backups-rhel-8-64-bit
  - linux-debug-aubsan-compile-required
  - linux-x86-dynamic-compile
  - linux-x86-dynamic-debug-compile-required
  - macos
  - macos-arm64
  - macos-debug-suggested
  - rhel8
  - rhel8-debug-asan
  - rhel8-debug-asan-all-feature-flags
  - rhel8-debug-asan-classic-engine
  - rhel8-debug-aubsan-lite
  - rhel8-debug-suggested
  - rhel8-debug-ubsan
  - rhel8-debug-ubsan-all-feature-flags
  - rhel8-debug-ubsan-classic-engine
  - rhel-8-arm64
  - rhel93
  - rhel93-arm64
  - suse15
  - ubi8
  - ubuntu1604-container
  - ubuntu1804-container
  - windows-compile-required
  - windows-debug-suggested
