build_variant_large_distro_exceptions:
  - amazon
  - amazon2
  - debian10
  - debian92
  - enterprise-amazon2
  - enterprise-amazon2-arm64
  - enterprise-debian10-64
  - enterprise-debian92-64
  - enterprise-linux-64-amazon-ami
  - enterprise-macos
  - enterprise-macos-cxx20
  - enterprise-macos-arm64
  - enterprise-rhel-67-s390x
  - enterprise-rhel-70-64-bit
  - enterprise-rhel-70-64-bit-no-libunwind
  - enterprise-rhel-71-ppc64le
  - enterprise-rhel-71-ppc64le-inmem
  - enterprise-rhel-72-s390x
  - enterprise-rhel-72-s390x-inmem
  - enterprise-rhel-80-64-bit
  - enterprise-rhel-80-64-bit-coverage
  - enterprise-rhel-81-ppc64le
  - enterprise-rhel-82-arm64
  - enterprise-suse12-64
  - enterprise-suse12-s390x
  - enterprise-suse15-64
  - enterprise-ubuntu1804-arm64
  - enterprise-ubuntu1804-ppc64le
  - enterprise-ubuntu1804-s390x
  - enterprise-ubuntu2004-arm64
  - hot_backups-rhel-70-64-bit
  - linux-64-ephemeralForTest
  - macos
  - macos-debug-suggested
  - rhel70
  - rhel80
  - rhel-82-arm64
  - suse12
  - suse15
  - ubi8
  - ubuntu1604-container
  - ubuntu1804-container
  - ubuntu1604-debug
  - ubuntu1804-debug-asan
  - ubuntu1804-debug-asan-all-feature-flags
  - ubuntu1804-debug-asan-classic-engine
  - ubuntu1804-debug-aubsan-lite-required
  - ubuntu1804-debug-ubsan
  - ubuntu1804-debug-ubsan-all-feature-flags
  - ubuntu1804-debug-ubsan-classic-engine
