build_variant_large_distro_exceptions:
  - amazon
  - amazon2
  - amazon2022
  - amazon2022-arm64
  - debian10
  - debian11
  - enterprise-amazon2
  - enterprise-amazon2-arm64
  - enterprise-amazon2022
  - enterprise-amazon2022-arm64
  - enterprise-debian10-64
  - enterprise-debian11-64
  - enterprise-linux-64-amazon-ami
  - enterprise-macos
  - enterprise-macos-rosetta-2
  - enterprise-macos-arm64
  - enterprise-rhel-67-s390x
  - enterprise-rhel-70-64-bit
  - enterprise-rhel-71-ppc64le
  - enterprise-rhel-71-ppc64le-inmem
  - enterprise-rhel-72-s390x
  - enterprise-rhel-72-s390x-inmem
  - enterprise-rhel-80-64-bit
  - enterprise-rhel-80-64-bit-coverage
  - enterprise-rhel-81-ppc64le
  - enterprise-rhel-82-arm64
  - enterprise-rhel-83-s390x
  - enterprise-rhel-90-64-bit
  - enterprise-rhel-90-arm64
  - enterprise-suse12-64
  - enterprise-suse12-s390x
  - enterprise-suse15-64
  - enterprise-ubuntu1804-arm64
  - enterprise-ubuntu1804-ppc64le
  - enterprise-ubuntu1804-s390x
  - enterprise-ubuntu2004-arm64
  - enterprise-ubuntu2204-arm64
  - hot_backups-rhel-70-64-bit
  - macos
  - macos-arm64
  - macos-debug-suggested
  - rhel70
  - rhel80
  - rhel80-debug-asan
  - rhel80-debug-asan-all-feature-flags
  - rhel80-debug-asan-classic-engine
  - rhel80-debug-aubsan-lite
  - rhel80-debug-suggested
  - rhel80-debug-ubsan
  - rhel80-debug-ubsan-all-feature-flags
  - rhel80-debug-ubsan-classic-engine
  - rhel-82-arm64
  - rhel90
  - rhel90-arm64
  - suse12
  - suse15
  - ubi8
  - ubuntu1604-container
  - ubuntu1804-container
