#######################################
#             Variable                #
#######################################
variables:
# Used when the tests it runs depend only on mongod, mongos, the jstestshell and the tools.
# THIS HAS COPIES IN
# - etc/evergreen_yml_components/definitions.yml
# - etc/evergreen_yml_components/tasks/components/aggregation_framework/resmoke_tasks.yml
# - etc/evergreen_yml_components/tasks/components/change_streams/resmoke_tasks.yml
# - etc/evergreen_yml_components/tasks/components/field_level_encryption/resmoke_tasks.yml
# - etc/evergreen_yml_components/tasks/components/querying/resmoke_tasks.yml
# - etc/evergreen_yml_components/tasks/components/security/resmoke_tasks.yml
# ANY MODIFICATIONS HERE SHOULD ALSO BE MADE IN THOSE FILES
- &task_template
  name: template
  depends_on:
  - name: archive_dist_test_debug
  commands:
  - func: "do setup"
  - func: "run tests"
    vars:
      resmoke_args: --help
      resmoke_jobs_max: 0  # No cap on number of jobs.


#######################################
#               Tasks                 #
#######################################
tasks:
- <<: *task_template
  name: external_auth
  tags: ["assigned_to_component_security"]
  commands:
  - func: "f_expansions_write"
  - func: "do setup"
  - func: "f_expansions_write"
  - func: "run tests"
    vars:
      resmoke_jobs_max: ${external_auth_jobs_max|4}
      resmoke_args: --excludeWithAnyTags=requires_domain_controller

- <<: *task_template
  name: external_auth_aws
  tags: ["assigned_to_component_security"]
  commands:
  - func: "f_expansions_write"
  - func: "do setup"
  - func: "f_expansions_write"
  - command: subprocess.exec
    params:
      binary: bash
      silent: true
      args:
      - "src/evergreen/external_auth_aws_setup.sh"
  - func: "run tests"

- <<: *task_template
  name: external_auth_oidc
  tags: ["assigned_to_component_security"]
  commands:
  - func: "f_expansions_write"
  - func: "do setup"
  - func: "f_expansions_write"
  - command: subprocess.exec
    params:
      binary: bash
      args:
      - "src/evergreen/external_auth_oidc_setup.sh"
  - func: "run tests"
    vars:
      resmoke_jobs_max: ${external_auth_oidc_jobs_max|1}

- <<: *task_template
  name: external_auth_oidc_azure
  tags: ["assigned_to_component_security"]
  commands:
  - func: "f_expansions_write"
  - func: "do setup"
  - func: "f_expansions_write"
  - command: subprocess.exec
    params:
      binary: bash
      args:
      - "src/evergreen/external_auth_azure_setup.sh"
  - func: "run tests"
  - command: subprocess.exec
    params:
      binary: bash
      args:
      - "src/evergreen/external_auth_azure_teardown.sh"

- <<: *task_template
  name: external_auth_windows
  tags: ["assigned_to_component_security"]
  commands:
  - func: "do setup"
  - func: "run tests"
    vars:
      suite: external_auth
      resmoke_args: --includeWithAnyTags=requires_domain_controller
