version: 1.0.0
filters:
  - "*chunk_migration_command*":
    approvers:
      - 10gen/server-cluster-scalability
  - "*transition_from_dedicated*":
    approvers:
      - 10gen/server-cluster-scalability
  - "*transition_to_dedicated*":
    approvers:
      - 10gen/server-cluster-scalability
  - "configsvr_add_*":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_check_*":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_commit*":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_coordinator*":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_create_database_command.cpp":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_drop_index_catalog_command.cpp":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_ensure_chunk_version_is_greater_than_command.cpp":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_get_historical_placement_info.cpp":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_merge_all_chunks_on_shard_command.cpp":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_merge_chunks_command.cpp":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_refine_collection_shard_key_command.cpp":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_remove*":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_repair_sharded_collection_chunks_history_command.cpp":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_reset_placement_history_command.cpp":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_set*":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_split_chunk_command.cpp":
    approvers:
      - 10gen/server-catalog-and-routing
  - "configsvr_update_zone_key_range_command.cpp":
    approvers:
      - 10gen/server-catalog-and-routing
  - "placement_history*":
    approvers:
      - 10gen/server-catalog-and-routing
  - "set_cluster*":
    approvers:
      - 10gen/server-catalog-and-routing
  - "sharding_catalog_*":
    approvers:
      - 10gen/server-catalog-and-routing
